### ISSUE TITLE
ERR_REQUIRE_ESM on new version

### ISSUE THREAD

**Issue by corioste** [glidejs/glide#627]
Got this version after updating the package to 3.6.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/@glidejs/glide/dist/glide.js from /home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js not supported.
glide.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename glide.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/@glidejs/glide/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.UbIB (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:6664:18)
    at __webpack_require__ (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:23:31)
    at Module.RXBc (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:3435:14)
    at __webpack_require__ (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:23:31)
    at Object.3 (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:269:18)
    at __webpack_require__ (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:23:31)
    at /home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:91:18
    at Object.<anonymous> (/home/cr1sg/Projects/ReactProjects/site/packages/landing/.next/server/pages/index.js:94:10)
    at requirePage (/home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/next/dist/next-server/server/require.js:1:1519)
    at loadComponents (/home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/next/dist/next-server/server/load-components.js:1:1442)
    at async /home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/next/dist/build/utils.js:23:2348
    at async Span.traceAsyncFn (/home/cr1sg/Projects/ReactProjects/site/packages/landing/node_modules/next/dist/telemetry/trace/trace.js:6:584) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}

**Comment by mariaRomeroiTech** [comment]
I am seeing this too

**Comment by zolzaya** [comment]
any updates?

**Comment by dessalines** [comment]
Same

**Comment by ericmorand** [comment]
Am I right to assume that the issue comes from NextJS? If so, was an issue created there?

**Comment by dessalines** [comment]
Any webpack project.

**Comment by ericmorand** [comment]
There is no such thing as a webpack project - it is nonsensical. Do you mean that the issue appears when you bundle your code with webpack? If so, did you open an issue in their repository?

**Comment by dessalines** [comment]
> There is no such thing as a webpack project - it is nonsensical. 

I don't want to argue semantics, there are lots of projects that use webpack. 

> If so, did you open an issue in their repository?

No because this is a glide-specific issue; I have many other dependencies that are being handled fine, including a downgraded version of this one. You need to remove `type: module` from the package json for this to work with both commonjs and esm projects again.
